name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            sudo apt-get -y update
            sudo apt-get install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            cd home
            sudo mv /home/newuser/* /var/www/html 

    - name: SSH Deploy on AWS EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_USER: ${{ secrets.USERNAME }}
        SSH_PASSWORD: ${{ secrets.PASSWORD }}
        SSH_HOST: ${{ secrets.HOST }}
        SSH_PORT: ${{ secrets.PORT }}
        SOURCE: "./"
        TARGET: ${{ secrets.TARGET }}
